name: Build Velvet

on:
  push:
    branches: [$default-branch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Build for Modrinth
        run: packwiz modrinth export

      - name: Build for CurseForge
        run: packwiz curseforge export

      - name: Upload Modrinth to GitHub Releases
        uses: actions/upload-artifact@v2
        with:
          name: velvet
          path: velvet-*.mrpack
          if-no-files-found: error

      - name: Upload CurseForge to GitHub Releases
        uses: actions/upload-artifact@v2
        with:
          name: velvet
          path: velvet-*.zip
          if-no-files-found: error
